// <auto-generated />
using System;
using FamilyModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyModel.Migrations
{
    [DbContext(typeof(PlantsSourceContext))]
    [Migration("20240507043123_idk")]
    partial class idk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyModel.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("FamilyId")
                        .HasName("PK__Table__41D82F6B84CD1217");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("FamilyModel.Gene", b =>
                {
                    b.Property<int>("GenusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenusId"));

                    b.Property<string>("Charecteristic")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<decimal?>("cost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GenusId")
                        .HasName("PK__Table__110363700F6A1A72");

                    b.HasIndex("FamilyId");

                    b.ToTable("Genus");
                });

            modelBuilder.Entity("FamilyModel.Gene", b =>
                {
                    b.HasOne("FamilyModel.Family", "Family")
                        .WithMany("Genus")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("FK_Genus_Family");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("FamilyModel.Family", b =>
                {
                    b.Navigation("Genus");
                });
#pragma warning restore 612, 618
        }
    }
}
